export const browserMethodsInput = `
  browser.get()
  browser.get(page)
  browser.driver.get('about:blank')
  browser.refresh()
  browser.navigate().forward()
  browser.navigate().back()
  browser.wait(5000)
  browser.getTitle()
  browser.getCurrentUrl()
  browser.setLocation('faq')
  browser.debugger()
  browser.findElement(by.css('.list'))
  browser.driver.findElement(by.css('.list'))
  // Everything below this is removed via codemods
  browser.restart()
  browser.restartSync()
  browser.ignoreSynchronization = true
  browser.manage().timeouts().implicitlyWait(15000)
  browser.driver.manage().timeouts().setScriptTimeout(55)
  browser.waitForAngular()
  browser.waitForAngularEnabled()
  browser.pause()
  browser.getId()
  `

export const browserMethodsOutput = `
  cy.visit()
  cy.visit(page)
  cy.visit('about:blank')
  cy.reload()
  cy.go('forward')
  cy.go('back')
  cy.wait(5000)
  cy.title()
  cy.location('href')
  cy.get('#faq').scrollIntoView()
  cy.debug()
  cy.get('.list')
  cy.get('.list')
  `